FROM public.ecr.aws/lambda/python:3.12

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY lambda_refresh.py ${LAMBDA_TASK_ROOT}/lambda_refresh.py

CMD ["lambda_refresh.lambda_handler"]
